# Site settings
title: xixi
description: xixi's portfolio :)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lenix Lobo
user_description: I am currently studying Information Technology at the Pune Institute of Computer Technology. I love Rendering stuff and Machine Learning.
user_title: Aspiring Graphics Programmer
email: lenixlobo@gmail.com
twitter_username: lenixlobo
github_username:  lenixlobo
gplus_username:  xixi

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
